[options]
; ============================================================
; Odoo Configuration - TP2 HA Master-Master
; Copier ce fichier dans odoo-node1/ et odoo-node2/
; Adapter db_host selon le nœud
; ============================================================

addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

; Base de données
db_host = db1           ; db2 pour le nœud 2
db_port = 5432
db_user = odoo
db_password = OdooSecure@2024
db_name = odoo
db_maxconn = 64

; Serveur
http_port = 8069
longpolling_port = 8072
workers = 4             ; Adapter selon les vCPU (2 x nb_cpus)
max_cron_threads = 2

; Performance
limit_memory_hard = 2684354560    ; 2.5 GB
limit_memory_soft = 2147483648    ; 2 GB
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200

; Proxy
proxy_mode = True       ; Obligatoire si derrière HAProxy/ALB

; Logs
logfile = /var/log/odoo/odoo.log
log_level = info
log_db = False

; Sécurité
admin_passwd = AdminMaster@2024    ; À changer en production !

; Sessions (partagées entre nœuds via Redis si dispo, sinon fichier)
session_store = file
